robot-dreams-currency-api:
  url: https://robot-dreams-de-api.herokuapp.com
  auth:
    endpoint: /auth
    payload: { "username": "rd_dreams", "password": "djT6LasE" }
  api:
    endpoint: /out_of_stock